### ISSUE TITLE
Add documentation for existing functionality in `PlayFabBuddy.Cli`

### ISSUE THREAD

**Issue by Structed** [Annonator/PlayFabBuddy#37]
**Is your feature request related to a problem? Please describe.**
There is currently no documentation on how to use `PlayFabBuddy.Cli`.

**Describe the solution you'd like**
Create basic documentation on:
* Configuration
* Usage of the existing commands:
  * `players create`
  * `players delete`

**Describe alternatives you've considered**
Using a help system directly in-app.
This is currently not implemented, but could be great way for new users to explore PlayFabBuddy.Cli.

**Comment by Structed** [comment]
Have added a PR for the docs!

**Comment by Annonator** [comment]
Thanks for your contribution! 

As far as I remember there is some default help build into the cli? Maybe a better documentation arround the commands might help to improve cli self help capabilities?
