### ISSUE TITLE
Delete PlayFab Players using remote information

### ISSUE THREAD

**Issue by Annonator** [Annonator/PlayFabBuddy#40]
**Is your feature request related to a problem? Please describe.**
We want to make sure we can delete users reliably based on real user data coming directly from a playfab title, not from a internally managed list. This will help resolving #39 

**Describe the solution you'd like**
When deleting players, I'm able to pass in additional search criteria, for example, delete all users from the title that were created between now and 2 days ago, or that are assigned to a specific segment.

To achieve this, we could use PlayFab Insights by connecting to the Azure Data Explorer (ADX) and use the data from there like `['events.all'] | where FullName_Name == "entity_created"` to get a list of players and their player accounts, from there we can then trigger a deletion based on the ID's. 

Data we are getting:
```
{
	"PlayFabEnvironment": {
		"Application": "mainserver",
		"Vertical": "master",
		"Commit": "*****",
		"Cloud": "main"
	},
	"EventNamespace": "com.playfab",
	"Timestamp": "2022-01-21T15:03:05.4480780Z",
	"EntityType": "title_player_account",
	"SourceType": "BackEnd",
	"EventName": "entity_created",
	"EntityId": "4FA72A0F4B433D13",
	"EventId": "*****",
	"EntityLineage": {
		"TitleId": "*****",
		"MasterPlayerAccountId": "A834A9F43DF99DBB",
		"TitlePlayerAccountId": "4FA72A0F4B433D13",
		"NamespaceId": "****"
	},
	"Source": "PlayFab",
	"EntityChain": "title_player_account!*****/*****/A834A9F43DF99DBB/4FA72A0F4B433D13/"`
}
```

Maybe have the repository handle this to keep the command / use case simple as this is a infrastructure concern.

**Comment by Structed** [comment]
Love the idea! However, we would need to add Azure authentication, wouldn't we?
Perhaps it's not so much of a big deal if you already use a Microsoft Account - but what if you are using PlayFab login to GameManager?

**Comment by Annonator** [comment]
We can use the Kusto C# SDK to connect to the PF insights instance managed by PF. We need to register a AAD application that gets access to the DB: https://docs.microsoft.com/en-us/gaming/playfab/features/insights/connectivity/creating-aad-app-for-insights

Once we done that we can access it through the kusto c# sdk.
https://docs.microsoft.com/en-us/gaming/playfab/features/insights/connectivity/connecting-kusto-csharp-to-insights

This is not ideal but i still think this is the best option we have.

**Comment by Structed** [comment]
I think there is a better, PlayFab native option: Using segments.

In every Title, there are a few pre-defined Segments, including the `All Players` Segment:
![image](https://user-images.githubusercontent.com/29922/152345191-feb32967-4773-4ca1-a0cc-a1d22f00b4dd.png)

1. Query all segments: https://docs.microsoft.com/en-us/rest/api/playfab/admin/play-stream/get-all-segments?view=playfab-rest
2. Get the ID of the `All Players` segment
2. Query the `All Players` Segment by ID: https://docs.microsoft.com/en-us/rest/api/playfab/admin/play-stream/get-players-in-segment?view=playfab-rest
3. Delete Players

**Comment by Annonator** [comment]
sounds good, give it a try :)

**Comment by Structed** [comment]
Work on this has started in https://github.com/structed/PlayFabBuddy/tree/gh-40-delete-players-by-segment

**Comment by Structed** [comment]
Tasks:

- [x] Implement deletion of all `Master Player Accounts` with a given segment
- [ ] Prevent deletion of `Master Player Accounts` which have multiple `Title Players`
- [ ] Implement progress display
- [ ] Add verbose output: User info
- [ ] Add Unit Tests
- [ ] Document feature

**Comment by Structed** [comment]
@Annonator what kind of output would you find useful?

- Number of removed accounts
- Account ID
- Account name
- Other?

**Comment by Annonator** [comment]
I think the number of accounts deleted is relevant for the CLI display, maybe we log out a list of the deleted users (MasterAccountd, TItlePlayerAccountId) into a file if the users wants to?

**Comment by Structed** [comment]
yes, but I would keep that to the verbose output. We have a progress bar anyways.
fort he non-verbose, how about only showing the count?
